### ISSUE TITLE
Default MEAS_INTERVAL might be too short

### ISSUE THREAD

**Issue by git1k2** [UnravelTEC/Raspi-Driver-SCD30#4]
Hi, thanks for this code! 

I was running it with the default `MEAS_INTERVAL = 1` but the measurements seemed off. I'm now running it with a 60 second interval and the values are more what I expect. The sensor is connected with a short lead next to a RPi3.

Measured change:
temp: dropped 3 degC
hum: rose 4%
ppm: dropped from 700 to 400 ppm

Maybe a longer default interval would be better?

_CO2 screenshot_
![co2](https://user-images.githubusercontent.com/48857344/56089682-e3b66e80-5e96-11e9-9ff1-a5a36e3c2608.png)

**Comment by species** [comment]
Thanks for your observations!
NDIR CO₂ measurement is extremely dependent on temperature and humidity (thats's why the SHT31 is on the board).
If you measure more often, the sensor heats up more - and if the sensor heats up unevenly (the chamber is hotter than the SHT31 measures), the results are off.

The measurement interval is highly dependent on the use case - if you want to observe instant changes in CO₂ levels, choose a short interval. If you want accurate measurements, keep the SCD30 at a uniform temperature, compensate for it or or choose a longer interval.

How is your sensor mounted, inside a box, maybe near a hot Raspberry Pi?

**Comment by git1k2** [comment]
Sounds reasonable, thanks!

The sensor is mounted with the recommended stand of height, on another board, not inside a box.

**Comment by species** [comment]
Note on the measurement interval: observations show that if you change the interval, you need to recalibrate the sensor.

We chose the short interval because of the faster response time. Feel free to adjust to your needs.

**Comment by tymm** [comment]
@species just to be sure: recalibration works by just putting the sensor outdoor while collecting measurements?
